spring:
  application:
    name:
      trade-mediator-api
  
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: true
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
        generate_statistics: ${SHOW_SQL}

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}


server:
  port: ${APP_PORT:8080}

app:
  insertMockDataOnStartup: ${INSERT_MOCK_DATA}